dubbo:
  application:
    name: loveread-manager-web
  registry:
    address: zookeeper://192.168.25.130:2181
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 10MB