server:
  port: 8081

mybatis:
  config-location: classpath:mybatis/SqlMapConfig.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  datasource:
    username: root
    password: 666999
    url: jdbc:mysql://192.168.25.130:3307/aiyue
#    url: jdbc:mysql://localhost:3306/aitao
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

dubbo:
  application:
    name: loveread-manager
  registry:
    address: zookeeper://192.168.25.130:2181
  scan:
    basePackages: cn.neusoft.loveread.manager.service