mybatis:
  config-location: classpath:mybatis/SqlMapConfig.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  datasource:
    username: root
    password: 666999
    url: jdbc:mysql://192.168.25.130:3307/aiyue
    #    url: jdbc:mysql://localhost:3306/aitao
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    solr:
      host: http://192.168.25.130:8984/solr/collection2
#      host: http://192.168.25.130:8984/solr
#      repositories:
#        enabled: true
#      zk-host: 192.168.25.130:2182,192.168.25.130:2183,192.168.25.130:2184
  activemq:
    user: admin
    password: admin
    broker-url: tcp://192.168.25.130:61616
    pool:
      enabled: true
      max-connections: 50
    packages:
      trust-all: false

dubbo:
  application:
    name: loveread-search
  registry:
    address: zookeeper://192.168.25.130:2181
  scan:
    basePackages: cn.neusoft.loveread.search.service
  protocol:
    port: 20882